version: 0.2

phases:
  build:
    commands:
      - >-
        aws ecr get-login-password --region $AWS_REGION | 
        docker login --username AWS --password-stdin 
        $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t potto-loris .
      - >-
        docker tag potto-loris:latest 
        $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/potto-loris:latest
      - >-
        docker push 
        $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/potto-loris:latest
